//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBORwebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LIBOREntities : DbContext
    {
        public LIBOREntities()
            : base("name=LIBOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SOFR> SOFRs { get; set; }
    
        public virtual ObjectResult<SP_INS_SOFR_Result> SP_INS_SOFR(Nullable<int> id, Nullable<System.DateTime> date, Nullable<decimal> sOFR_Index, Nullable<decimal> average_30Days, Nullable<decimal> average_90Days, Nullable<decimal> average_180Days)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var sOFR_IndexParameter = sOFR_Index.HasValue ?
                new ObjectParameter("SOFR_Index", sOFR_Index) :
                new ObjectParameter("SOFR_Index", typeof(decimal));
    
            var average_30DaysParameter = average_30Days.HasValue ?
                new ObjectParameter("Average_30Days", average_30Days) :
                new ObjectParameter("Average_30Days", typeof(decimal));
    
            var average_90DaysParameter = average_90Days.HasValue ?
                new ObjectParameter("Average_90Days", average_90Days) :
                new ObjectParameter("Average_90Days", typeof(decimal));
    
            var average_180DaysParameter = average_180Days.HasValue ?
                new ObjectParameter("Average_180Days", average_180Days) :
                new ObjectParameter("Average_180Days", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_INS_SOFR_Result>("SP_INS_SOFR", idParameter, dateParameter, sOFR_IndexParameter, average_30DaysParameter, average_90DaysParameter, average_180DaysParameter);
        }
    }
}
